services:
  tanku-bot:
    image: testimage
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:8085:8085
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - APP_ID=${APP_ID}
      - CLAN_ID=${CLAN_ID}
      - ALLOWED_ACCOUNT_ID=${ALLOWED_ACCOUNT_ID}
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8085
    volumes:
      - tanku-bot:/tanku-bot/db
volumes:
  tanku-bot:
    external: true
