services:
  tanku-bot:
    image: testimage
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 127.0.0.1:8085:8085
    restart: always
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8085
    volumes:
      - ${PWD}/tanku.db:/tanku-bot/tanku.db